name: Terraform CI

on:
  push:
    branches:
      - main
    paths:
      - "**/*.tf"
      - "**/*.tfvars"
      - ".github/workflows/terraform.yml"

  pull_request:
    branches:
      - main
    paths:
      - "**/*.tf"
      - "**/*.tfvars"
      - ".github/workflows/terraform.yml"

  workflow_dispatch:

permissions:
  contents: read

jobs:
  terraform-checks:
    name: Terraform Validation
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: environments/dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Terraform format check
        working-directory: .
        run: terraform fmt -check -recursive

      - name: Terraform init without backend
        run: terraform init -backend=false

      - name: Terraform validate
        run: terraform validate

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4

      - name: Initialize TFLint
        run: tflint --init

      - name: Run TFLint
        working-directory: .
        run: tflint --recursive
